### ISSUE TITLE
docker compose nginx无法使用

### ISSUE THREAD

**Issue by XXQJDR** [httpsok/httpsok#13]
## 1 执行`docker compose up -d`出现以下问题
```sh
> [nginx 3/3] RUN curl -s https://get.httpsok.com/ | bash -s token:
1.392 2024-06-27 01:07:28 Create directory /root/.httpsok success.
1.395 2024-06-27 01:07:28 Create directory /root/.httpsok/backups success.
2.026 2024-06-27 01:07:29 save token to /root/.httpsok/token
2.027 2024-06-27 01:07:29 Installing httpsok.
3.070 2024-06-27 01:07:30 Install httpsok complete.
3.074 no crontab for root
3.076 2024-06-27 01:07:30 Installing cron job.
3.079 no crontab for root
3.084 2024-06-27 01:07:30 Install cron job complete.
3.085 2024-06-27 01:07:30 Installing alias
3.088 2024-06-27 01:07:30 Found profile: /root/.bashrc
3.090 2024-06-27 01:07:30 Installing alias to '/root/.bashrc'
3.097 2024-06-27 01:07:30 OK, Close and reopen your terminal to start using httpsok
3.799 main: line 194: ps: command not found
3.813 2024-06-27 01:07:30 os-name: Debian GNU/Linux 12 (bookworm)
3.814 2024-06-27 01:07:30 version: nginx/1.27.0
3.815 2024-06-27 01:07:30 nginx-config: /etc/nginx/nginx.conf
3.817 2024-06-27 01:07:30 nginx-config-home: /etc/nginx
3.818 2024-06-27 01:07:30 nginx-bin: nginx
3.819 2024-06-27 01:07:30 httpsok-uuid: AD185E1B-3B37-495C-82CC-964DDFBC17A4
3.820
3.820 Httpsok make SSL easy.     https://httpsok.com/
3.820 version: 1.14.0
3.820 TraceID: 54b5a0eac2580d765c729c12fd6fe6a6
3.820
4.519 2024-06-27 01:07:31 No SSL certificate was detected.
4.519
4.520 2024-06-27 01:07:31 Please refer to resolve the issue. https://httpsok.com/doc/reference/nginx-config.html
4.521
------
failed to solve: process "/bin/sh -c curl -s https://get.httpsok.com/ | bash -s token" did not complete successfully: exit code: 4
```

> 但不使用Dockerfile文件构建镜像，直接在容器中执行脚本不会出现该问题

## 2 DockerfileNginx文件内容如下
```sh
FROM nginx:latest

# 安装crontab
RUN apt-get -y update && apt-get -y install cron

# 下载脚本并执行
RUN curl -s https://get.httpsok.com/ | bash -s token
```

## 3 docker-compose.yml文件内容如下
```yaml
version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/certs"
    networks:
      - anime-net
    restart: always
networks:
  anime-net:
    name: anime
```

## 4 nginx.conf文件内容如下
```sh
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
    server {
        listen  443 ssl;
        server_name animerecorder.asia;

        # 设置ssl证书文件路径
        ssl_certificate /certs/_.animerecorder.asia.pem;
        ssl_certificate_key /certs/_.animerecorder.asia.key;

        ssl_session_timeout 5m;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security "max-age=31536000";

        # 访问日志
        access_log /var/log/nginx/anime-recorder.asia.https.log;
        location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
                root   html;
        }
    }
}
```
